name: Github Pages Deploy

on:
  push:
    branches:
      - "stage"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_API_KEYS: ${{secrets.REACT_APP_API_KEYS}}
          REACT_APP_API_BASE_URI: ${{secrets.REACT_APP_API_BASE_URI}}
          REACT_APP_API_BASE_IMAGE_URL: ${{secrets.REACT_APP_API_BASE_IMAGE_URL}}
          REACT_APP_FIREBASE_API_KEY: ${{secrets.REACT_APP_FIREBASE_API_KEY}}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGEBUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGEBUCKET}}
          REACT_APP_FIREBASE_MESSAGEIN_SENDER_ID: ${{secrets.REACT_APP_FIREBASE_MESSAGEIN_SENDER_ID}}
          REACT_APP_FIREBASE_APP_ID: ${{secrets.REACT_APP_FIREBASE_APP_ID}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
